Swift 4.2
Boerworz/Gagat pull request #7
Opened 2018-10-14 16:15 UTC by douglashill

This migrates all three targets to Swift 4.2. It also removes a deprecated API call in the example app that was not needed and resulted in a warning with Xcode 10.

2018-10-15 18:32 UTC, Boerworz requested changes
Thank you for doing this, Douglas! 🌟 It's been on my todo list for a while 😅

Unfortunately, the changes in this pull request break Objective-C compatibility due to the limited `@objc` inference in Swift 4. It seems like the fix is to add `@objcMembers` to the public classes in the `GagatObjectiveC` target. More information about the `@objc`-related changes in Swift 4 can be found in [the original proposal](
https://github.com/apple/swift-evolution/blob/master/proposals/0160-objc-inference.md) (where the [Re-enabling `@objc` inference within a class hierarchy](https://github.com/apple/swift-evolution/blob/master/proposals/0160-objc-inference.md#re-enabling-objc-inference-within-a-class-hierarchy) section is especially relevant for this case).

If you could make the needed changes I'd be happy to verify and get this merged!

2018-10-21 11:28 UTC, douglashill commented
Since the public API is so small I thought it made more sense to add `@objc` to each public method rather than `@objcMembers` on the classes.

I also added an Objective-C example so it’s easier to test if the Objective-C framework is working. If you don’t want that in the repo I’m happy to delete that commit, but I think it’s worth the noise.

2018-10-22 18:50 UTC, Boerworz approved these changes

2018-10-22 18:54 UTC, Boerworz commented
Thanks again for taking the time to make these changes, Douglas! Adding an Objective-C example was a great idea 👌

I've tested the changes locally and everything seems to work as expected. I'll get a new release out soon 🚀

2018-10-22 18:55 UTC, merged

2018-10-23 09:20 UTC, douglashill commented
Yeah if the Objective-C wrapper is being maintained there needs to be an easy way to check it works.

Thank you for creating and open-sourcing Gagat!